import type { Metadata } from "next";

const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://ratchawatmuaythai.com";
const SITE_NAME = "Ratchawat Muay Thai";

interface PageMetaOptions {
  title: string;
  description: string;
  path?: string;
  noIndex?: boolean;
}

// OG and Twitter images are auto-generated by Next.js from the file
// convention at src/app/opengraph-image.jpg + twitter-image.jpg. We do not
// set openGraph.images or twitter.images per page; Next inherits from the
// root layout convention. To override per route, drop a route-local
// opengraph-image.jpg next to that page's page.tsx.
export function generatePageMeta({
  title,
  description,
  path = "",
  noIndex = false,
}: PageMetaOptions): Metadata {
  const url = `${SITE_URL}${path}`;

  return {
    title,
    description,
    alternates: {
      canonical: url,
    },
    openGraph: {
      title,
      description,
      url,
      siteName: SITE_NAME,
      locale: "en_US",
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
    },
    ...(noIndex && {
      robots: {
        index: false,
        follow: false,
      },
    }),
  };
}

export { SITE_URL, SITE_NAME };
